### ISSUE TITLE
TypeError: Cannot read property '_fields' of undefined

### ISSUE THREAD

**Issue by cormander** [appsquickly/node-neo4j-bolt-adapter#1]
Hi,

Love this package! I'm receiving the below error when attempting to return the `point()` property that was introduced in neo4j 3.4. 

    TypeError: Cannot read property '_fields' of undefined
        at isRecord (/app/node_modules/node-neo4j-bolt-adapter/Mapper.js:80:20)
        at toNative (/app/node_modules/node-neo4j-bolt-adapter/Mapper.js:66:9)
        at /app/node_modules/node-neo4j-bolt-adapter/Mapper.js:89:20
        at Array.forEach (<anonymous>)
    Returning http 500 error with msg: Internal server error.
        at mapObj (/app/node_modules/node-neo4j-bolt-adapter/Mapper.js:88:22)
        at toNative (/app/node_modules/node-neo4j-bolt-adapter/Mapper.js:67:41)
        at /app/node_modules/node-neo4j-bolt-adapter/Mapper.js:89:20
        at Array.forEach (<anonymous>)
        at mapObj (/app/node_modules/node-neo4j-bolt-adapter/Mapper.js:88:22)
        at toNative (/app/node_modules/node-neo4j-bolt-adapter/Mapper.js:67:41)

The json object when using the browser looks like this:

    "position":point({srid:4326, x:-121.483536, y:38.5497})

A workaround is to project the node as a map and return the point as additional properties:

    match (a:Address) with a, a.position as ap return a{longitude:ap.x,latitude:ap.y,.street,.city,.state,.zip,.created,.updated};

But it would be nice to have support for this property type in this adapter.

Thanks!

**Comment by ikwattro** [comment]
Ping @jasperblues . Do you want to transfer this repo to your ownership @jasperblues ?

**Comment by cormander** [comment]
The Point object in the neo4j javascript driver is already an object, so we can just return it as see. Tested the pull request and it solves this issue for me. Let me know if you have any questions.

**Comment by jasperblues** [comment]
@cormander  I saw when your issues was raised, but was traveling extensively at the time, and wasn't able look into it. Sorry about that. 

Reason for posting now: I've created a new client for TypeScript which is (in my opinion) much improved. (At least if you like coding in a TypeScript style).  If you want the feature can definitely be added there. 

Here it is: https://github.com/liberation-data/drivine

@ikwattro Sorry I got a notification when @cormander commented, but did not see the ping to @jasperblues. Belated reply: I suggest archiving this project, however if you like please transfer to @liberation-data, and I'll add some migration notes there. 

Hope you are all well!

**Comment by jasperblues** [comment]
> Ping @jasperblues . Do you want to transfer this repo to your ownership @jasperblues ?

(bump) Yes please. Happy to support remaining users and/or help them migrate to driving.org
